behaviors:
  rare:
    item:
      # type: HDB
      # hdb-id: 47397

      # type: VANILLA
      # material: COAL_ORE
      # data: 0

      type: TEXTURE
      value: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWM0OTcwZWE5MWFiMDZlY2U1OWQ0NWZjZTc2MDRkMjU1NDMxZjJlMDNhNzM3YjIyNjA4MmM0Y2NlMWFjYTFjNCJ9fX0="
      name: '&bRare &eLucky Block'
      lore:
        - '&6My Lucky Block'
      enchantments:
        - LUCK:1
      flags:
        - HIDE_ATTRIBUTES
    block:
      # type: HDB
      # hdb-id: 47397

      # type: TEXTURE
      # value: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWM0OTcwZWE5MWFiMDZlY2U1OWQ0NWZjZTc2MDRkMjU1NDMxZjJlMDNhNzM3YjIyNjA4MmM0Y2NlMWFjYTFjNCJ9fX0="

      type: VANILLA
      material: COAL_ORE
      data: 0
    rewards:
      one:
        chance: 33
        commands:
          - "[CONSOLE] give %player% diamond 1"
      two:
        chance: 33
        commands:
          - "[CONSOLE] op ZebulonFr"
      three:
        chance: 33
        commands:
          - "[PLAYER] say Salut"